project:
  type: website

website:
  title: "OT WIKI"
  site-url: https://ucsb-library-research-data-services.github.io/math-wiki-test
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true

editor: visual

